"""Guard the generated demo page against the aesthetic it was redesigned away from.

`demo/noema.html` is generated by `demo/export.py`. A previous redesign was edited
into the generated file directly and was silently reverted the next time anyone ran
the generator, so these assertions pin the properties that regression would break.
"""

import pathlib
import re

import pytest

HTML = pathlib.Path(__file__).resolve().parents[1] / "demo" / "noema.html"
pytestmark = pytest.mark.skipif(not HTML.exists(), reason="run demo/export.py first")


@pytest.fixture(scope="module")
def page():
    return HTML.read_text()


@pytest.mark.parametrize("banned", [
    "color-scheme: dark",     # the page is printed on paper, not screen-black
    "-webkit-font-smoothing",  # thins ink on a light background
    "image-rendering:pixelated",
    "border-radius:6px",
    "box-shadow: 0 0",         # depth is not simulated; there is no depth
    "#fcfdbf", "#000004",      # magma endpoints, built for a dark field
    "4b9fff",                  # the old accent
])
def test_forbidden_aesthetic_is_absent(page, banned):
    assert banned not in page


def test_ramp_floor_matches_the_page_colour(page):
    # Unfilled raster cells show the page through. If stop 0 and --paper ever drift,
    # the field draws a visible rectangle edge against the surrounding paper.
    paper = re.search(r"--paper:\s*(#[0-9A-Fa-f]{6})", page).group(1)
    ramp0 = re.search(r"--ramp-0:\s*(#[0-9A-Fa-f]{6})", page).group(1)
    assert paper.lower() == ramp0.lower()


def test_faces_are_inlined_so_the_page_needs_no_network(page):
    assert page.count("@font-face") == 3
    assert "data:font/woff2;base64," in page
    assert "https://" not in page.split("<style>")[1].split("</style>")[0]


def test_tabular_figures_are_one_declaration(page):
    # Splitting the two keywords across declarations drops the first, so the live
    # readout would start shifting horizontally as its digits change.
    assert "font-variant-numeric:tabular-nums slashed-zero" in page


def test_the_synthetic_boundary_is_stated_in_the_caption(page):
    # The disclosure belongs at the point of contact, not two screens away, so pin
    # it to the caption specifically. Wrapping is incidental; collapse it.
    caption = " ".join(page.split("<figcaption>")[1].split("</figcaption>")[0].split())
    assert "synthetic" in caption
    assert "not an experimental recording" in caption


def test_the_loop_stops_when_the_tab_is_hidden(page):
    assert "visibilitychange" in page
