"""Guard the generated demo page against the aesthetic it was redesigned away from.

`demo/noema.html` is generated by `demo/export.py`. A previous redesign was edited
into the generated file directly and was silently reverted the next time anyone ran
the generator, so these assertions pin the properties that regression would break.
"""

import pathlib
import re

import pytest

HTML = pathlib.Path(__file__).resolve().parents[1] / "demo" / "noema.html"
pytestmark = pytest.mark.skipif(not HTML.exists(), reason="run demo/export.py first")


@pytest.fixture(scope="module")
def page():
    return HTML.read_text()


@pytest.mark.parametrize("banned", [
    "-webkit-font-smoothing",  # thins ink on a light background
    "image-rendering:pixelated",
    "border-radius:6px",
    "box-shadow: 0 0",         # depth is not simulated; there is no depth
    "#fcfdbf", "#000004",      # magma endpoints, built for a dark field
    "4b9fff",                  # the old accent
])
def test_forbidden_aesthetic_is_absent(page, banned):
    assert banned not in page


def test_the_page_defaults_to_light(page):
    # Dark is offered, not assumed. The default palette is the printed one; dark only
    # applies under an explicit mode attribute or the reader's own system preference.
    root = page.split(":root{")[1].split("}")[0]
    assert "color-scheme:light" in root.replace(" ", "")
    assert 'data-mode="dark"' in page


def test_both_modes_keep_the_ramp_anchored_to_the_page(page):
    # Quiet firing must recede into the background in either mode. If stop 0 and the
    # page colour drift apart, the field draws a visible edge against the page.
    import re as _re
    for mode in ("light", "dark"):
        block = page.split(':root[data-mode="dark"]')[1 if mode == "dark" else 0]
        paper = _re.search(r"--paper:\s*(#[0-9A-Fa-f]{6})", block).group(1)
        ramp0 = _re.search(r"--ramp-0:\s*(#[0-9A-Fa-f]{6})", block).group(1)
        assert paper.lower() == ramp0.lower(), f"{mode}: ramp floor is not the page colour"


def test_one_face_carries_the_whole_page(page):
    assert page.count("@font-face") == 1
    assert "data:font/woff2;base64," in page
    assert "https://" not in page.split("<style>")[1].split("</style>")[0]


def test_tabular_figures_are_one_declaration(page):
    # Splitting the two keywords across declarations drops the first, so the live
    # readout would start shifting horizontally as its digits change.
    assert "font-variant-numeric:tabular-nums slashed-zero" in page


def test_the_page_no_longer_claims_to_be_synthetic(page):
    # The previous page ran a synthetic spiking system and disclosed it in seven places.
    # This one plays real recordings, so a leftover disclaimer would be false in the
    # opposite direction — and the real source has to be named instead.
    assert "synthetic" not in page.lower()
    assert "DANDI:000954" in page


def test_both_objectives_ship(page):
    # The contrast between the two training objectives is the finding. If one model
    # silently stops being exported the page still renders, just without its argument.
    assert '"multistep"' in page and '"onestep"' in page


def test_parity_is_reported_as_measured_against_a_gate(page):
    # A passing number nobody can see the size of is not evidence, so the page prints
    # both the measurement and the threshold and never the word "verified".
    assert "against a gate of 2 in a thousand" in page
    assert "verified" not in page.lower()


def test_the_centred_metric_is_the_one_explained(page):
    # Raw correlation is roughly twice centred on this data. Which one leads is the
    # page's central honesty decision, so it must be stated, not just plotted.
    assert "centred" in page
    assert "average profile" in page or "average firing" in page


def test_the_page_states_it_does_not_beat_a_constant(page):
    # The model is below a flat, strictly causal forecast at every horizon. The page once
    # compared only against repeating the last bin — the weaker of the two floors — and
    # reported a fourfold advantage on that basis. Both floors must be drawn, and the
    # shortfall must be in the prose rather than left for a reader to infer from the plot.
    assert "seed_mean" in page and "seed mean held flat" in page
    assert "does not beat" in page


def test_canvas_heights_are_multiples_of_the_channel_count(page):
    # A 150px canvas over 176 channels silently drops 26 of them while the deck and the
    # aria-labels claim 176. Heights must divide evenly so every channel gets a row.
    heights = [int(m) for m in re.findall(r"\.reg[^{]*\{[^}]*height:(\d+)px", page)]
    assert heights, "no register heights found"
    assert all(h % 176 == 0 for h in heights), f"heights not divisible by 176: {heights}"


def test_the_reveal_is_not_painted_before_it_is_held(page):
    # The forecast is held alone before the recording arrives; that pause is the argument.
    # Painting the revealed state during boot showed the answer and then retracted it.
    assert "if (painted){ render(H); plot(); }" in page
